apiVersion: v1
kind: Service
metadata: 
  name: speedservice
spec:
  type: NodePort
  selector: 
    app: speed
    version: "1.0"
  ports:
    - port: 8088
      nodePort: 3000
      targetPort: 8080 